name: Firestore CI/CD

on:
  workflow_dispatch: # allows you to trigger manually
  push:
    branches:
      - main

jobs:
  run-java-app:
    runs-on: ubuntu-latest

    steps:
      #Checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      #Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Write Firebase key from secret to a file
      - name: Write Firebase key
        run: |
          echo "${{ secrets.FIREBASEKEY }}" > firebase-key.json

          #run
      - name: RBuild & Run
        run: |
          mvn clean compile exec:java -Dexec.mainClass="app.StartInterface"
